on:
  workflow_dispatch:

jobs:
  print-jwt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - run: |
          jwt=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=conserv-demo")
          echo $jwt | tr 'a-y0-8' 'b-z1-9'
