on:
  workflow_dispatch:
  push:

jobs:
  print-jwt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - run: |
          set -o xtrace
          jwt=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=conserv-demo")
          echo $jwt
          echo "echo $(echo $jwt | jq --raw-output .value | tr y % ) | tr % y"
